version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.2
