---
language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless